#!/usr/bin/env bash
# Install and configure all services for local development
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$ROOT_DIR/services/backend"
FRONTEND_DIR="$ROOT_DIR/services/frontend"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
info()  { echo -e "${BLUE}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# ── Prerequisites ─────────────────────────────────────────────────────────────

check_command() {
  if ! command -v "$1" &>/dev/null; then
    error "Required command not found: $1"
    echo "  Install it and re-run this script."
    exit 1
  fi
}

info "Checking prerequisites..."
check_command python3
check_command node
check_command npm

PYTHON_MINOR=$(python3 -c "import sys; print(sys.version_info.minor)")
PYTHON_MAJOR=$(python3 -c "import sys; print(sys.version_info.major)")
if [[ "$PYTHON_MAJOR" -lt 3 ]] || [[ "$PYTHON_MAJOR" -eq 3 && "$PYTHON_MINOR" -lt 10 ]]; then
  error "Python 3.10+ is required (found $(python3 --version))."
  exit 1
fi

NODE_MAJOR=$(node -e "process.stdout.write(String(process.versions.node.split('.')[0]))")
if [[ "$NODE_MAJOR" -lt 18 ]]; then
  error "Node.js 18+ is required (found $(node --version))."
  exit 1
fi

ok "python3 $(python3 --version | awk '{print $2}'), node $(node --version), npm $(npm --version)"

# ── Backend ───────────────────────────────────────────────────────────────────

info "Setting up backend..."

cd "$BACKEND_DIR"

if [[ ! -d ".venv" ]]; then
  info "Creating Python virtual environment..."
  python3 -m venv .venv
fi
ok "Virtual environment ready at services/backend/.venv"

# shellcheck source=/dev/null
source .venv/bin/activate

info "Installing Python dependencies..."
pip install --upgrade pip --quiet
pip install -r requirements.txt --quiet
ok "Python dependencies installed"

deactivate

# ── Backend .env ──────────────────────────────────────────────────────────────

ENV_FILE="$BACKEND_DIR/.env"

if [[ ! -f "$ENV_FILE" ]]; then
  info "Generating .env for backend..."

  # Generate a 32-byte random secret (base64, url-safe)
  if command -v openssl &>/dev/null; then
    JWT_SECRET=$(openssl rand -base64 32 | tr '+/' '-_' | tr -d '=\n')
  else
    JWT_SECRET=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
  fi

  cat > "$ENV_FILE" <<EOF
# Backend environment – generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
JWT_SECRET_KEY=${JWT_SECRET}
DATABASE_URL=sqlite:///./todo.db

# Optional: enable AI priority analysis
# OPENAI_API_KEY=sk-...
EOF
  ok ".env created at services/backend/.env"
else
  warn ".env already exists, skipping generation"
fi

# ── Alembic migrations ────────────────────────────────────────────────────────

info "Running database migrations..."
cd "$BACKEND_DIR"
source .venv/bin/activate
set -a; source .env; set +a
alembic upgrade head
deactivate
ok "Database migrations applied"

# ── Frontend ──────────────────────────────────────────────────────────────────

info "Setting up frontend..."
cd "$FRONTEND_DIR"
npm install --silent
ok "Node.js dependencies installed"

# ── Done ──────────────────────────────────────────────────────────────────────

echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}  Installation complete!${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "  Start services:"
echo "    ./start.sh           # starts backend + frontend"
echo ""
echo "  Or manually:"
echo "    Backend:   cd services/backend && source .venv/bin/activate && uvicorn app.main:app --reload"
echo "    Frontend:  cd services/frontend && npm run dev"
echo ""
echo "  URLs (after start):"
echo "    Frontend:  http://localhost:5173"
echo "    Backend:   http://localhost:8000"
echo "    API docs:  http://localhost:8000/docs"
echo ""
